woola/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.views.generic import TemplateView
from django.apps import apps

from rest_framework import routers, serializers, viewsets


# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

"""
Auto generate REST API URL for all retailers using Router
"""

#


urlpatterns = patterns('',
    url(r'^$', 'core.views.index', name='home'),
    url(r'^about/$',
        TemplateView.as_view(template_name='pages/about.html'),
        name="about"),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    # User management
    url(r'^users/', include("users.urls", namespace="users")),
    url(r'^accounts/', include('allauth.urls')),

    # Uncomment the next line to enable avatars
    url(r'^avatar/', include('avatar.urls')),

    # Your stuff: custom urls go here

    # Retailers
    url(r'^retailer/', include('core.urls')),

    url(r'^api/v1/crawler/$', 'core.views.crawler', name='crawler'),

    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


"""
Get RESTful APIs from all Retailer apps
"""

REST_APIs = patterns('',)

# Get all installed applications
all_installed_apps = apps.get_models()

# Filter all non related apps and keep only Retailer apps.
all_retailers = filter(lambda app: 'retailer_name' in dir(app), all_installed_apps)

# Loop through all retailers object
for retailer in all_retailers:
    # Create URL pattern
    url_pattern = url(r'^api/v1/', include(retailer.app_name + '.urls'))
    # Store API URL pattern in REST_APIs
    REST_APIs.append(url_pattern)

# Create final URL pattern
urlpatterns += REST_APIs

woola/users/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url

from users import views

urlpatterns = patterns('',
    # URL pattern for the UserListView  # noqa
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),
    # URL pattern for the UserRedirectView
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),
    # URL pattern for the UserDetailView
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
    # URL pattern for the UserUpdateView
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
)

woola/templates/base.html
{% load staticfiles i18n %}<!DOCTYPE html>
<html lang="en" ng-app{{ ng_app_name }}>
  <head>
    <meta charset="utf-8">
    <title>{% block title %}Woola{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="Derek Lin">

    {% block css %}
    <!-- CSS Reset -->
    <link rel="stylesheet" href="{% static 'css/normalize.css' %}">
    <!-- Latest compiled and minified Foundation CSS -->
    <link rel="stylesheet" href="{% static 'css/foundation.min.css' %}">
    <!-- Your stuff: Third-party css libraries go here -->
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
    <!-- This file store project specific CSS -->
    <link href="{% static 'css/project.css' %}" rel="stylesheet">
    {% endblock %}

    <!-- Your stuff: Third-party javascript libraries go here -->
    <script src="{% static 'js/vendor/modernizr.js' %}"></script>
  </head>

  <body>
    <header>
      <div class="row">
        <div class="large-3 columns">
          <h1>WOOLA</h1>
        </div>
        <div class="large-9 columns">
          <nav class="navbar">
            <ul class="right">
              <li><a href="{% url 'home' %}">Home</a></li>
              <li><a href="{% url 'about' %}">About</a></li>
              {% if request.uthenticated %}
              <li><a href="{% url 'users:detail' request.user.username  %}">{% trans "My Profile" %}</a></li>
              <li><a href="{% url 'account_logout' %}">{% trans "Logout" %}</a></li>
              {% else %}
              <li><a href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a></li>
              <li><a href="{% url 'account_login' %}">{% trans "Log In" %}</a></li>
              {% endif %}
            </ul>
          </nav>
        </div>
      </div>
    </header>

    <section class="hero">
      <div class="row">
        <div class="large-12 columns">
          <i class="fa fa-gift fa-5x"></i>
          <p>Woola is my one of pet projects.  It's a great tool to track your favorite item when it goes on sale.</p>
          <a href="#" class="button radius info">Why Me</a>
        </div>
      </div>
    </section>

    <main>
      <div class="row">
        <div class="large-12 columns">
        {% if messages %}
            {% for message in messages %}
                <div class="alert {% if message.tags %}alert-{{ message.tags }}"{% endif %}>{{ message }}</div>
            {% endfor %}
        {% endif %}
        </div>
      </div>
      <br>
      {% block content %}
      {% endblock content %}
    </main>
    {% block modal %}
    {% endblock modal %}

    <footer>
        <div class="row">
          <div class="small-12 columns">
            <hr>
          </div>
          <div class="small-12 columns">
            <nav>
             <ul>
               <li><a href="{% url 'home' %}">Home</a></li>
               <li><a href="{% url 'about' %}">About</a></li>
               {% if request.uthenticated %}
               <li><a href="{% url 'users:detail' request.user.username  %}">{% trans "My Profile" %}</a></li>
               <li><a href="{% url 'account_logout' %}">{% trans "Logout" %}</a></li>
               {% else %}
               <li><a href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a></li>
               <li><a href="{% url 'account_login' %}">{% trans "Log In" %}</a></li>
               {% endif %}
             </ul>
            </nav>
          </div>
          <div class="small-12 columns">
            <p class="copyright text-center">Copyright &copy; {% now "Y" %}</p>
          </div>
        </div>
    </footer>
    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block jquery %}
      <!-- Latest JQuery -->
      <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    {% endblock %}

    {% block angular %}
      <!-- Latest AngularJS -->
      <script src="//ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js"></script>
      <script src="//ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular-resource.min.js"></script>
      <script src="//ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular-cookies.min.js"></script>
    {% endblock %}

    {% block angular_app %}
        <!-- Angular app files -->
    {% endblock %}

    {% block foundation %}
      <!-- Latest minified Foundation javascript -->
      <script src="{% static 'js/foundation.min.js' %}"></script>
    {% endblock %}

    {% block javascript %}
      <!-- Your stuff: Third-party javascript libraries go here -->

      <!-- place project specific Javascript in this file -->
      <script src="{% static 'js/project.js' %}"></script>
    {% endblock javascript %}
  </body>
</html>